### ISSUE TITLE
Investigate moving generated code to package-specific sub-directories.

### ISSUE THREAD

**Issue by malcolmgreaves** [Nitro/avro-codegen#12]
Currently all generated code is put into 1 directory. The files have correct package declarations and names. However, currently, if 2 generated schemas have the same name (but different packages), then they'll overwrite the same file.

Possible work-arounds:

- Generate package-specific sub-directories. Put all files into these sub-directories.
- Add unique prefix to each file to eliminate the possibility of collision.

**Comment by malcolmgreaves** [comment]
@mkolod

**Comment by ebiggs** [comment]
I vote for package-specific sub-directories as that follows convention and I believe plays more nicely in scala-ide?

**Comment by ebiggs** [comment]
#17 resolves this bug.
