### ISSUE TITLE
"Two many schema objects" exception

### ISSUE THREAD

**Issue by e8kor** [Nitro/avro-codegen#20]
CachedSchemaRegistryClient use IdentityHashMap which compare's instances of schemas by its references. To fix problem I propose in Generated companion objects  make  `def schema: org.apache.avro.Schema` as `val schema: org.apache.avro.Schema` to avoid problem of constantly growing schema cache.

[CachedSchemaRegistryClient Issue](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/confluent-platform/gkmtn2FO4Ug/IIsp8tZHT0QJ)
[Related Issue on Github](https://github.com/confluentinc/schema-registry/issues/172)

**Comment by malcolmgreaves** [comment]
Fixed by #21

**Comment by malcolmgreaves** [comment]
Included in the `0.3.4` release, which is now on sonatype.

**Comment by e8kor** [comment]
Super, thanks.
