### ISSUE TITLE
Inability to use inter-dependent schemas defined in multiple files

### ISSUE THREAD

**Issue by malcolmgreaves** [Nitro/avro-codegen#3]
Currently, avro-codegen cannot handle inter-dependent schemas defined in multiple files. The work around is to define all inter-dependent schemas within the same file. This approach does not scale well and results in annoying-to-read-and-comprehend `.asvc` files.

Moving forward, we should widen the search scope for schemas during parsing.

**Comment by ebiggs** [comment]
By interdependent do you mean allowing for identical/compatible restatements? Like if you had a record with the same name defined in two different .avsc files, it would check to make sure they're identical/compatible and if they are create only one corresponding case class? Or are you thinking about having B defined only once in B.avsc file and all other files would only reference B by name?

**Comment by pkinsky** [comment]
@ebiggs: the second case. The official avro schema parser class (as far as I know) only supports parsing single avsc files, not collections of files that contain cross-file references.

**Comment by ebiggs** [comment]
@pkinsky you're right. Also the official avro schema parser class requires that the full definition precede any by-name references, so any multi file strategy using the official parser would need a file order defined. We'd need to write a parser that lifts these restrictions, but that should be fairly easy if we were to just sit on top of a json parser like spray-json. If you agree with this over all approach I wouldn't mind coming up with a pull request... 

I'm thinking it would also be able to handle identical redefinitions, throwing a parser exception if the redefinition is incompatible.

Additionally we'd probably want a different file extension than avsc to avoid confusion? Perhaps a avsp?for avro-schema-part(ial)?

**Comment by pkinsky** [comment]
@ebiggs: that sounds really cool, you might also want to put together your own case class AST for your parser to output (IIRC the avro schema class mainly relies on boolean flags and nullable values).  That approach sounds reasonable and I'd be happy to work with you to put together a pull request.

Have you considered creating this avro schema parser as a standalone library and publishing it separately so that multiple projects can use it? I'd be happy to start with it as a part of avro codegen, but this seems like it might also be useful elsewhere (eg: a preprocessor utility that takes some set of .avsp files and creates a single large .avsc file that can be used with other avro tools)

**Comment by malcolmgreaves** [comment]
This would make for an excellent PR! As an overall strategy, I think it'd have to process as: (1) parse each .avsc file, turn all definitions into intermediate representations; (2) resolve dependencies for each intermediate representation (e.g.`User` has a `Homepage` field, which is an Avro schema). If the resolution fails, it would result in a distinct failure result. Something similar to `Try`'s `Success` / `Failure` (not an exception).

This would be a pretty big PR, as it would imply making a new parser, defining an intermediate description of Avro schemas in-memory, then doing a resolution. Totally happy to make this happen, however!

**Comment by ebiggs** [comment]
Ok since there appears to be interest I'll stub out something simple that works an solicit some feedback. It does sound like it might be useful outside nitro avro codegen, but I'll still be positioning this as something I'd rather donate than own...

**Comment by pkinsky** [comment]
@ebiggs we can absolutely take over long term maintenance, donations are always appreciated :smiley:

**Comment by ebiggs** [comment]
So my fork now has a completely untested solution. Gonna write unit tests and play whack-a-mole, but any feedback would be much appreciated as well.

**Comment by malcolmgreaves** [comment]
Awesome stuff! If you want to open up a PR, we can use it to comment as you continue to develop.
