### ISSUE TITLE
Ensure new partial schema parser is integrated with codegen step.

### ISSUE THREAD

**Issue by malcolmgreaves** [Nitro/avro-codegen#6]
(1) make sure that the codegen part uses the new partial schema parser
(2) have it work with both `.avsc` and `.avsp`
(3) update the end-to-end (`./e2e.sh`) tests to include partial schemas, verify that they are parsed correctly

Targeting a 0.3.1 release

**Comment by ebiggs** [comment]
I'm not sure if this is obvious, but I want to mention that it would be possible to run the .avsc through the module alongside all the .avsp, which would make it possible for the .avsp files may reference schema from the .avsc files. To make sure .avsc files are canonical though it would be best to first try and run them through the org.apache parser before running them through the module.

**Comment by pkinsky** [comment]
@ebiggs: thanks for the tip, I'll try that approach.

**Comment by malcolmgreaves** [comment]
Fixed w/ Paul today. Going out as `0.3.1` release: https://github.com/Nitro/avro-codegen/commit/7d1e9b7b1cf2c51b3dfeaaef3460270a3dd7a68e
