### ISSUE TITLE
Schema Permutations with invariant type parameters.

### ISSUE THREAD

**Issue by ebiggs** [Nitro/avro-codegen#7]
I'm curious if there's an appetite for this possibly crazy enhancement:

Let's define a Tuple2.avsp like so:
```
{
  "type"="record",
  "name"="Tuple2",
  "fields"= [
    {"name":"_1", "type":"A"},
    {"name":"_2", "type":"B"}
  ]
}
```
Currently, unless A and B are defined in another avsp file the AvModule.fromPartials parser will throw an exception reporting A and B as referencing missing definitions.

What if, instead of throwing an exception, we took Tuple2 to be an avro schema constructor and A and B would be placeholders for some definition or defined reference? This would then allow us to construct variations of the Tuple2 schema by mapping the references to definitions. We'd need to apply some naming convention to the constructed schema to uniquely identify the constructed schema.

Take for example:

```
val avModule = AvModule.fromPartials(tuple2Str)
avModule.construct("Tuple2")("A" -> AvInt, "B" -> AvString)
shouldBe
{
  "type"="record",
  "name"="Tuple2_Int_String",
  "fields"= [
    {"name":"_1", "type":"int"},
    {"name":"_2", "type":"string"}
  ]
}
```

This concept would then map to type parameters in the codegen scala classes:

```scala
final case class Tuple2[A : TypeTag, B : TypeTag](
    _1: A,
    _2: B
  ) extends com.nitro.scalaAvro.runtime.GeneratedMessage 
   with com.nitro.scalaAvro.runtime.Message[Tuple2[A, B]] { ... }
```

The TypeTags would allow us to then map to the corresponding Definition allowing us to complete the schema construction as shown above.

In order to achieve this, we would need to move the Av* AST and AvModule to runtime, create a centralized place to store the avro partials and avro constructors, and the schema would need to be built at runtime instead of being defined as string literals.

Known limitation:
Type parameters could be scala types already mapped to avro primitives, or records but they could not be Vector or Option due to type erasure with those types. A work around could be to create higher kind constructors? i.e. something like this:

```scala
object Tuple2 {
  def apply[A1[T] : TypeTag, A2 : TypeTag, B1[T] : TypeTag, B2 : TypeTag] = apply[A1[A2], B1[B2]]
}
```

Tuple2[Option, Int, Vector, String] shouldBe Tuple2[Option[Int], Vector[String]]

But this would eventually break down, what if you wanted, for example, Tuple2[Vector[Option[Int]]], Option[Vector[String]]]? You could create a HKT constructor to the next degree, but is there really a desire to do so?

Not a Limitation:
I don't believe we would be limited when nesting records, so it might make more sense to forgo an Array and create a List avro schema constructor, then you could have arbitrary nesting, like List[List[List[List[String]]]]

**Comment by pkinsky** [comment]
How about this instead? (based on scalapb custom base traits http://trueaccord.github.io/ScalaPB/customizations.html)

```
package com.foo.bar

trait Request {
  id: Long
}
```

```
{
  "type"="record",
  "name"="FooBarRequest",
  "baseTrait"="com.foo.bar.Request"
  "fields"= [
    {"name":"foo", "type":"int"},
    {"name":"bar", "type":"string"},
    {"name":"id", "type":"long"}
  ]
}
```

This would generate something like:

```
final case class FooBarRequest(
    foo: Int,
    bar: String,
    id: Long
  ) extends com.nitro.scalaAvro.runtime.GeneratedMessage 
   with com.nitro.scalaAvro.runtime.Message[FooBarRequest] 
   with com.foo.bar.Request
```

This would require rewriting the code generator class to work directly with the classes produced by your parser to allow adding custom fields like `baseTrait` to schemas.

**Comment by ebiggs** [comment]
Yeah this would be great as well, although I do believe I have a need for both...

**Comment by pkinsky** [comment]
I'm not sure I understand the use case, can you provide a concrete example where this would be useful?

I'd prefer to implement features like this as requiring new custom json fields (now that we're using the parser you built), generating code differently if there's an undefined reference (instead of just failing with an exception) could lead to unintuitive behavior if someone accidentally leaves a reference undefined. If we implement something like this, I'd prefer to make it explicit, something like:

```
{
  "type": "record",
  "name": "Tuple2",
  "abstract_fields" : ["_1", "_2"]
  "fields"= [
    {"name":"_1", "type":"A"},
    {"name":"_2", "type":"B"}
  ]
}
```

**Comment by ebiggs** [comment]
Would it not be useful for the tuple example? I do like your suggestion of making it explicit through a property.

**Comment by ebiggs** [comment]
Giving this some more thought, it's really trying to fight the avro feature set. It's a bad abstraction. It's probably a better approach in general to have your scala entities reflect avro idioms than avro schema reflect scala idioms.

So I think this should be closed.

Sorry for wasting anybody's mental bandwidth evaluating this.

**Comment by malcolmgreaves** [comment]
No worries @ebiggs ! Discussions are always welcome. You didn't waste anyone's mental bandwidth =D

**Comment by pkinsky** [comment]
@ebiggs this was an interesting discussion, any ideas re: possible improvements are always welcome :smile:
